### ISSUE TITLE
embind-test-01: when compiling with -O2 referencing C++ classes/methods from JavaScript does not work anymore

### ISSUE THREAD

**Issue by cee-dee** [cee-dee/emscripten-tests#1]
Within directory embind-test-01, compile with
  emcc --bind -o test.js test.cpp 
and open up test.html within Firefox-browser. Then, within the console you see "11" and "hello".

Then, compile with
  emcc --bind -o test.js test.cpp -O2
and open up test.html within Firefox-browser. Then, within the console you see "TypeError: Module.MyClass is not a constructor"

I'm using the portable SDK. "./emsdk list" gives:

The following individual tools exist:
      clang-incoming-32bit
      clang-incoming-64bit
      clang-master-32bit
X     clang-master-64bit INSTALLED
      emscripten-1.29.0
      emscripten-1.30.0
      emscripten-incoming-32bit
      emscripten-master-32bit
      emscripten-incoming-64bit
X     emscripten-master-64bit INSTALLED

The following Emscripten SDK versions are available:
      sdk-incoming-32bit
      sdk-incoming-64bit
      sdk-master-32bit
X     sdk-master-64bit INSTALLED

Items marked with \* are activated for the current user.

Any ideas why this is happening?

**Comment by kripken** [comment]
I can confirm this. cc @chadaustin @waywardmonkeys

**Comment by waywardmonkeys** [comment]
This seems to be referencing some files for a test case ... are those available?

**Comment by kripken** [comment]
Yes, in this repo (this isn't the emscripten repo).

**Comment by chadaustin** [comment]
I looked into this.  This looks related to meminit files.

The second script runs before the embind bindings run, because the first script doesn't actually run the bindings until the meminit XHR returns.

I would say this is expected but non-obvious behavior.  Perhaps one fix, @cee-dee, is to disable meminit files.

Another would be to not run the second script until the meminit file is loaded.  (I don't recall off the top of my head how to do that.)

**Comment by waywardmonkeys** [comment]
So, one thing that you could here is to wrap your code in:

``` javascript
Module.addOnPreMain(function() { ... });
```

Like this:

``` javascript
  <script>
    Module.addOnPreMain(function() {
      var instance = new Module.MyClass(10, "hello");
      instance.incrementX();
      console.log(instance.x); // 11
      instance.x = 20; // 20
      console.log(Module.MyClass.getStringFromInstance(instance)); // "hello"
      instance.delete();
    });
  </script>
```

That works for me with your sample @ `-O2` and solves the meminit file issue that @chadaustin identified.

**Comment by cee-dee** [comment]
Ah, ok. Makes sense for me! Thank you both very much! :+1:
